name: E2E Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 5 * * 1'
  workflow_dispatch:

jobs:
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: example-project/package-lock.json

      - name: Install dependencies
        run: npm install
        working-directory: ./example-project

      - name: Run example project with valid token
        run: node index.js ${{ secrets.SOURCE_TOKEN }}
        working-directory: ./example-project

      - name: Run example project with invalid token
        run: |
          if node index.js INVALID_TOKEN; then
            echo "This should have failed but didn't"
            exit 1
          else
            echo "Failed successfully"
          fi
        working-directory: ./example-project

  tests-bun:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [latest, 1.0.0]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install
        working-directory: ./example-project

      - name: Run example project with valid token
        run: bun run index.js ${{ secrets.SOURCE_TOKEN }}
        working-directory: ./example-project

      - name: Run example project with invalid token
        run: |
          if bun run index.js INVALID_TOKEN; then
            echo "This should have failed but didn't"
            exit 1
          else
            echo "Failed successfully"
          fi
        working-directory: ./example-project
